# Please add your Github ID and Allianz email below if you want to become a project maintainer of the
# Allianz Github organization. Read the maintainer guidelines first TODO.
#
# We cannot accept anomynous code contributions or anomynous project maintainers. Therefore all code maintainers 
# must acknowledge the terms and conditions of the DCO (https://developercertificate.org/). With the sign-of off
# you accept that your company email will be added to the git history and to this file. 

# Important: All changes to this file must be done by the affected persons themself!

---
cheld: christoph.held@allianz.com
cheld-demo: adsf@allianz.com
boez-za: adsf@google.com